// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Skywardkite/service-metrics/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// GetCounter provides a mock function for the type MockStorage
func (_mock *MockStorage) GetCounter(ctx context.Context, name string) (int64, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetCounter")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCounter'
type MockStorage_GetCounter_Call struct {
	*mock.Call
}

// GetCounter is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockStorage_Expecter) GetCounter(ctx interface{}, name interface{}) *MockStorage_GetCounter_Call {
	return &MockStorage_GetCounter_Call{Call: _e.mock.On("GetCounter", ctx, name)}
}

func (_c *MockStorage_GetCounter_Call) Run(run func(ctx context.Context, name string)) *MockStorage_GetCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_GetCounter_Call) Return(n int64, err error) *MockStorage_GetCounter_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStorage_GetCounter_Call) RunAndReturn(run func(ctx context.Context, name string) (int64, error)) *MockStorage_GetCounter_Call {
	_c.Call.Return(run)
	return _c
}

// GetGauge provides a mock function for the type MockStorage
func (_mock *MockStorage) GetGauge(ctx context.Context, name string) (float64, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetGauge")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (float64, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) float64); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetGauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGauge'
type MockStorage_GetGauge_Call struct {
	*mock.Call
}

// GetGauge is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockStorage_Expecter) GetGauge(ctx interface{}, name interface{}) *MockStorage_GetGauge_Call {
	return &MockStorage_GetGauge_Call{Call: _e.mock.On("GetGauge", ctx, name)}
}

func (_c *MockStorage_GetGauge_Call) Run(run func(ctx context.Context, name string)) *MockStorage_GetGauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_GetGauge_Call) Return(f float64, err error) *MockStorage_GetGauge_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *MockStorage_GetGauge_Call) RunAndReturn(run func(ctx context.Context, name string) (float64, error)) *MockStorage_GetGauge_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetrics provides a mock function for the type MockStorage
func (_mock *MockStorage) GetMetrics(ctx context.Context) (map[string]float64, map[string]int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMetrics")
	}

	var r0 map[string]float64
	var r1 map[string]int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string]float64, map[string]int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]float64); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]float64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) map[string]int64); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]int64)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockStorage_GetMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetrics'
type MockStorage_GetMetrics_Call struct {
	*mock.Call
}

// GetMetrics is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorage_Expecter) GetMetrics(ctx interface{}) *MockStorage_GetMetrics_Call {
	return &MockStorage_GetMetrics_Call{Call: _e.mock.On("GetMetrics", ctx)}
}

func (_c *MockStorage_GetMetrics_Call) Run(run func(ctx context.Context)) *MockStorage_GetMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_GetMetrics_Call) Return(stringToFloat64 map[string]float64, stringToInt64 map[string]int64, err error) *MockStorage_GetMetrics_Call {
	_c.Call.Return(stringToFloat64, stringToInt64, err)
	return _c
}

func (_c *MockStorage_GetMetrics_Call) RunAndReturn(run func(ctx context.Context) (map[string]float64, map[string]int64, error)) *MockStorage_GetMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockStorage
func (_mock *MockStorage) Ping() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockStorage_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *MockStorage_Expecter) Ping() *MockStorage_Ping_Call {
	return &MockStorage_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *MockStorage_Ping_Call) Run(run func()) *MockStorage_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_Ping_Call) Return(err error) *MockStorage_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Ping_Call) RunAndReturn(run func() error) *MockStorage_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// SaveMetrics provides a mock function for the type MockStorage
func (_mock *MockStorage) SaveMetrics(filePath string, gauges map[string]float64, counters map[string]int64) error {
	ret := _mock.Called(filePath, gauges, counters)

	if len(ret) == 0 {
		panic("no return value specified for SaveMetrics")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, map[string]float64, map[string]int64) error); ok {
		r0 = returnFunc(filePath, gauges, counters)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_SaveMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveMetrics'
type MockStorage_SaveMetrics_Call struct {
	*mock.Call
}

// SaveMetrics is a helper method to define mock.On call
//   - filePath string
//   - gauges map[string]float64
//   - counters map[string]int64
func (_e *MockStorage_Expecter) SaveMetrics(filePath interface{}, gauges interface{}, counters interface{}) *MockStorage_SaveMetrics_Call {
	return &MockStorage_SaveMetrics_Call{Call: _e.mock.On("SaveMetrics", filePath, gauges, counters)}
}

func (_c *MockStorage_SaveMetrics_Call) Run(run func(filePath string, gauges map[string]float64, counters map[string]int64)) *MockStorage_SaveMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 map[string]float64
		if args[1] != nil {
			arg1 = args[1].(map[string]float64)
		}
		var arg2 map[string]int64
		if args[2] != nil {
			arg2 = args[2].(map[string]int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_SaveMetrics_Call) Return(err error) *MockStorage_SaveMetrics_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_SaveMetrics_Call) RunAndReturn(run func(filePath string, gauges map[string]float64, counters map[string]int64) error) *MockStorage_SaveMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// SetCounter provides a mock function for the type MockStorage
func (_mock *MockStorage) SetCounter(ctx context.Context, name string, value int64) error {
	ret := _mock.Called(ctx, name, value)

	if len(ret) == 0 {
		panic("no return value specified for SetCounter")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = returnFunc(ctx, name, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_SetCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCounter'
type MockStorage_SetCounter_Call struct {
	*mock.Call
}

// SetCounter is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - value int64
func (_e *MockStorage_Expecter) SetCounter(ctx interface{}, name interface{}, value interface{}) *MockStorage_SetCounter_Call {
	return &MockStorage_SetCounter_Call{Call: _e.mock.On("SetCounter", ctx, name, value)}
}

func (_c *MockStorage_SetCounter_Call) Run(run func(ctx context.Context, name string, value int64)) *MockStorage_SetCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_SetCounter_Call) Return(err error) *MockStorage_SetCounter_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_SetCounter_Call) RunAndReturn(run func(ctx context.Context, name string, value int64) error) *MockStorage_SetCounter_Call {
	_c.Call.Return(run)
	return _c
}

// SetGauge provides a mock function for the type MockStorage
func (_mock *MockStorage) SetGauge(ctx context.Context, name string, value float64) error {
	ret := _mock.Called(ctx, name, value)

	if len(ret) == 0 {
		panic("no return value specified for SetGauge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, float64) error); ok {
		r0 = returnFunc(ctx, name, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_SetGauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetGauge'
type MockStorage_SetGauge_Call struct {
	*mock.Call
}

// SetGauge is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - value float64
func (_e *MockStorage_Expecter) SetGauge(ctx interface{}, name interface{}, value interface{}) *MockStorage_SetGauge_Call {
	return &MockStorage_SetGauge_Call{Call: _e.mock.On("SetGauge", ctx, name, value)}
}

func (_c *MockStorage_SetGauge_Call) Run(run func(ctx context.Context, name string, value float64)) *MockStorage_SetGauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_SetGauge_Call) Return(err error) *MockStorage_SetGauge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_SetGauge_Call) RunAndReturn(run func(ctx context.Context, name string, value float64) error) *MockStorage_SetGauge_Call {
	_c.Call.Return(run)
	return _c
}

// SetMetricsBatch provides a mock function for the type MockStorage
func (_mock *MockStorage) SetMetricsBatch(ctx context.Context, metrics []models.Metrics) error {
	ret := _mock.Called(ctx, metrics)

	if len(ret) == 0 {
		panic("no return value specified for SetMetricsBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []models.Metrics) error); ok {
		r0 = returnFunc(ctx, metrics)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_SetMetricsBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMetricsBatch'
type MockStorage_SetMetricsBatch_Call struct {
	*mock.Call
}

// SetMetricsBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - metrics []models.Metrics
func (_e *MockStorage_Expecter) SetMetricsBatch(ctx interface{}, metrics interface{}) *MockStorage_SetMetricsBatch_Call {
	return &MockStorage_SetMetricsBatch_Call{Call: _e.mock.On("SetMetricsBatch", ctx, metrics)}
}

func (_c *MockStorage_SetMetricsBatch_Call) Run(run func(ctx context.Context, metrics []models.Metrics)) *MockStorage_SetMetricsBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []models.Metrics
		if args[1] != nil {
			arg1 = args[1].([]models.Metrics)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_SetMetricsBatch_Call) Return(err error) *MockStorage_SetMetricsBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_SetMetricsBatch_Call) RunAndReturn(run func(ctx context.Context, metrics []models.Metrics) error) *MockStorage_SetMetricsBatch_Call {
	_c.Call.Return(run)
	return _c
}
