CREATE TABLE IF NOT EXISTS gauges (
    name    VARCHAR(255) PRIMARY KEY,
    value   DOUBLE PRECISION NOT NULL
);
CREATE TABLE IF NOT EXISTS counters (
    name    VARCHAR(255) PRIMARY KEY,
    value   INTEGER NOT NULL DEFAULT 0
);