// Code generated by MockGen. DO NOT EDIT.
// Source: internal/audit/event.go
//
// Generated by this command:
//
//	mockgen -source=internal/audit/event.go -destination=internal/audit/mocks/audit_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	audit "github.com/Skywardkite/service-metrics/internal/audit"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditPublisherInterface is a mock of AuditPublisherInterface interface.
type MockAuditPublisherInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuditPublisherInterfaceMockRecorder
	isgomock struct{}
}

// MockAuditPublisherInterfaceMockRecorder is the mock recorder for MockAuditPublisherInterface.
type MockAuditPublisherInterfaceMockRecorder struct {
	mock *MockAuditPublisherInterface
}

// NewMockAuditPublisherInterface creates a new mock instance.
func NewMockAuditPublisherInterface(ctrl *gomock.Controller) *MockAuditPublisherInterface {
	mock := &MockAuditPublisherInterface{ctrl: ctrl}
	mock.recorder = &MockAuditPublisherInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditPublisherInterface) EXPECT() *MockAuditPublisherInterfaceMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockAuditPublisherInterface) Publish(event audit.AuditEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Publish", event)
}

// Publish indicates an expected call of Publish.
func (mr *MockAuditPublisherInterfaceMockRecorder) Publish(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockAuditPublisherInterface)(nil).Publish), event)
}
