package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"text/template"
)

const templateStr = `
// Code generated by reset; DO NOT EDIT.
// This file was generated by reset.go

package {{.Package}}

{{range .Structs}}func (rs *{{.Name}}) Reset() {
    if rs == nil {
        return
    }
{{range .Fields}}
    {{.}}{{end}}
}

{{end}}`

type Struct struct {
	Name   string
	Fields []string
}

type TemplateData struct {
	Package string
	Structs []Struct
}

func main() {
	// данные окружения от go:generate
	fname := os.Getenv("GOFILE")
	pkg := os.Getenv("GOPACKAGE")
	dir := os.Getenv("PWD")

	// парсим файл
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, fname, nil, parser.ParseComments)
	if err != nil {
		panic(err)
	}

	resets := map[string]string{
		"int":     "0",
		"int64":   "0",
		"float64": "0",
		"string":  `""`,
		"bool":    "false",
	}

	// Собираем список всех структур с // generate:reset
	markedStructs := map[string]struct{}{}

	for _, d := range f.Decls {
		gen, ok := d.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE || gen.Doc == nil {
			continue
		}

		for _, c := range gen.Doc.List {
			if c.Text == "// generate:reset" {
				for _, spec := range gen.Specs {
					ts := spec.(*ast.TypeSpec)
					markedStructs[ts.Name.Name] = struct{}{}
				}
			}
		}
	}

	var structures []Struct

	for _, d := range f.Decls {
		gen, ok := d.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}

		if gen.Doc == nil {
			continue
		}

		hasMarker := false
		for _, c := range gen.Doc.List {
			if c.Text == "// generate:reset" {
				hasMarker = true
			}
		}
		if !hasMarker {
			continue
		}

		for _, spec := range gen.Specs {
			ts := spec.(*ast.TypeSpec)
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}

			var fields []string

			for _, f := range st.Fields.List {
				if len(f.Names) == 0 {
					continue
				}

				for _, name := range f.Names {
					switch t := f.Type.(type) {
					// Примитивы и структуры без указателя
					case *ast.Ident:
						// примитив
						if zero, ok := resets[t.Name]; ok {
							fields = append(fields, fmt.Sprintf("rs.%s = %s", name.Name, zero))
						} else if _, ok := markedStructs[t.Name]; ok {
							// вложенная структура с Reset
							fields = append(fields, fmt.Sprintf("if resetter, ok := rs.%s.(interface{ Reset() }); ok && rs.%s != nil {\n        resetter.Reset()\n    }", name.Name, name.Name))
						}
					// Указатель
					case *ast.StarExpr:
						switch ident := t.X.(type) {
						case *ast.Ident:
							// указатель на примитив
							if zero, ok := resets[ident.Name]; ok {
								fields = append(fields, fmt.Sprintf("if rs.%s != nil {\n        *rs.%s = %s\n    }", name.Name, name.Name, zero))
							} else if _, ok := markedStructs[ident.Name]; ok {
								// указатель на структуру с Reset
								fields = append(fields, fmt.Sprintf("if resetter, ok := rs.%s.(interface{ Reset() }); ok && rs.%s != nil {\n        resetter.Reset()\n    }", name.Name, name.Name))
							}
						}
					// слайсы
					case *ast.ArrayType:
						if t.Len != nil {
							continue
						}

						fields = append(fields, fmt.Sprintf("rs.%s = rs.%s[:0]", name.Name, name.Name))
					// мапа
					case *ast.MapType:
						fields = append(fields, fmt.Sprintf("clear(rs.%s)", name.Name))
					}
				}
			}

			structures = append(structures, Struct{
				Name:   ts.Name.Name,
				Fields: fields,
			})
		}
	}

	if len(structures) == 0 {
		return
	}

	tmpl := template.Must(template.New("reset").Parse(templateStr))

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, TemplateData{Package: pkg, Structs: structures}); err != nil {
		panic(err)
	}

	out := filepath.Join(dir, "reset.gen.go")
	if err := os.WriteFile(out, buf.Bytes(), 0644); err != nil {
		panic(err)
	}
}
