// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/service.go -destination=internal/service/mocks/service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Skywardkite/service-metrics/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricServiceInterface is a mock of MetricServiceInterface interface.
type MockMetricServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMetricServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockMetricServiceInterfaceMockRecorder is the mock recorder for MockMetricServiceInterface.
type MockMetricServiceInterfaceMockRecorder struct {
	mock *MockMetricServiceInterface
}

// NewMockMetricServiceInterface creates a new mock instance.
func NewMockMetricServiceInterface(ctrl *gomock.Controller) *MockMetricServiceInterface {
	mock := &MockMetricServiceInterface{ctrl: ctrl}
	mock.recorder = &MockMetricServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricServiceInterface) EXPECT() *MockMetricServiceInterfaceMockRecorder {
	return m.recorder
}

// GetAllMetrics mocks base method.
func (m *MockMetricServiceInterface) GetAllMetrics(ctx context.Context) (map[string]float64, map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMetrics", ctx)
	ret0, _ := ret[0].(map[string]float64)
	ret1, _ := ret[1].(map[string]int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllMetrics indicates an expected call of GetAllMetrics.
func (mr *MockMetricServiceInterfaceMockRecorder) GetAllMetrics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMetrics", reflect.TypeOf((*MockMetricServiceInterface)(nil).GetAllMetrics), ctx)
}

// GetMetric mocks base method.
func (m *MockMetricServiceInterface) GetMetric(ctx context.Context, metricType, metricName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetric", ctx, metricType, metricName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetric indicates an expected call of GetMetric.
func (mr *MockMetricServiceInterfaceMockRecorder) GetMetric(ctx, metricType, metricName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetric", reflect.TypeOf((*MockMetricServiceInterface)(nil).GetMetric), ctx, metricType, metricName)
}

// Ping mocks base method.
func (m *MockMetricServiceInterface) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockMetricServiceInterfaceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockMetricServiceInterface)(nil).Ping), ctx)
}

// SaveMetricsBatch mocks base method.
func (m *MockMetricServiceInterface) SaveMetricsBatch(ctx context.Context, metrics []models.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMetricsBatch", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMetricsBatch indicates an expected call of SaveMetricsBatch.
func (mr *MockMetricServiceInterfaceMockRecorder) SaveMetricsBatch(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMetricsBatch", reflect.TypeOf((*MockMetricServiceInterface)(nil).SaveMetricsBatch), ctx, metrics)
}

// UpdateMetric mocks base method.
func (m *MockMetricServiceInterface) UpdateMetric(ctx context.Context, metricType, metricName, metricValue string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetric", ctx, metricType, metricName, metricValue)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMetric indicates an expected call of UpdateMetric.
func (mr *MockMetricServiceInterfaceMockRecorder) UpdateMetric(ctx, metricType, metricName, metricValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetric", reflect.TypeOf((*MockMetricServiceInterface)(nil).UpdateMetric), ctx, metricType, metricName, metricValue)
}
